modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "LGPL-2.1"

[[mods]]
modId = "better_quest_popup"
version = "${version}"
displayName = "Better Quest Pop-up"
authors = "Katatsumuri.pan"
description = '''
"Better" quest pop-up for FTB Quests!
'''

[[dependencies.better_quest_popup]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_quest_popup]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_quest_popup]]
modId = "architectury"
mandatory = true
versionRange = "[6,)"
ordering = "AFTER"
side = "BOTH"
