modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPL-2.1"

[[mods]]
modId = "better_quest_popup"
version = "${version}"
displayName = "Better Quest Pop-up"
authors = "Katatsumuri.pan"
description = '''
"Better" quest pop-up for FTB Quests!
'''
logoFile = "assets/better_quest_popup/icon.png"

[[dependencies.better_quest_popup]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_quest_popup]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_quest_popup]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"
