# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.1
maven_group = kpan.bq_popup
archives_name = BetterQuestPopup-1.19.2
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.19.2
yarn_mappings = 1.19.2+build.28

# Dependencies
architectury_api_version = 6.6.92
fabric_loader_version = 0.16.9
fabric_api_version = 0.77.0+1.19.2
forge_version = 1.19.2-43.4.0
ftb_library_version=1902.4.1-build.315
ftb_teams_version=1902.2.14-build.165
ftb_quests_version=1902.5.9-build.399

# Optional Dependencies
teamreborn_energy_version=3.0.0